bases:
- ../../base
patchesStrategicMerge:
configMapGenerator:
- name: gateway-configmap
  behavior: merge
  files:
    - application.yaml
images:
 - name: elsapi/gateway
   newName: gateway
   newTag: latest
