management:
  endpoints:
    web:
      exposure:
        include: '*'
metrics:
  prometheus:
    enabled: true
server:
  port: 8070
spring:
  application:
    name: gateway
  redis:
    host: localhost
    port: 6379
  cloud:
    kubernetes:
      enabled: false
    gateway:
      discovery:
        locator:
          lowerCaseServiceId: true
          enabled: true
dekorate:
  kubernetes:
    group: jackbeaken
logging:
  #  level: INFO
  loggers:
    com.netflix.discovery.provider.DiscoveryJerseyProvider:
      level: NONE

