management:
  endpoints:
    web:
      exposure:
        include: '*'
metrics:
  prometheus:
    enabled: true
server:
  port: 8070
spring:
  application:
    name: gateway
  devtools:
    remote:
      secret=b4409eff-031a-48a5-ac36-4b74da00fd61
  redis:
    host: localhost
    port: 6379
logging:
  level:
    org.springframework.security: INFO



