version: '3.2' 

volumes:
  postgres-data: {}
  
services:

  redis:
    image: redis
    ports:
      - "6379:6379"

  eureka:
    image: springcloud/eureka
    ports:
      - "8761:8761"
     
  keycloak:
    image: jboss/keycloak:8.0.2
    ports:
      - "9090:8080"
    environment:
      KEYCLOAK_LOGLEVEL: INFO
      KEYCLOAK_USER: admin 
      KEYCLOAK_PASSWORD: admin
      DB_VENDOR: postgres
      DB_USER: keycloak
      DB_PASSWORD: p@ssword
      DB_ADDR: postgres
    depends_on:
      - postgres
      
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: keycloak
      POSTGRES_DB: keycloak
      POSTGRES_PASSWORD: p@ssword
    volumes:
      - postgres-data:/var/lib/postgresql/data
