# APP DEPLOYMENT

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    run: httpbin
  name: httpbin
spec:
  replicas: 1
  selector:
    matchLabels:
      run: httpbin-exposed
  template:
    metadata:
      labels:
        run: httpbin-exposed
    spec:
      serviceAccountName: chaos
      containers:
        - image: jackbeaken/httpbin
          name: httpbin
          ports:
            - containerPort: 8081
              protocol: TCP

---

# APP SERVICE

apiVersion: v1
kind: Service
metadata:
  labels:
    run: httpbin
  name: httpbin
spec:
  ports:
    - port: 8081
      protocol: TCP
      targetPort: 8081
  selector:
    run: httpbin-exposed
  type: NodePort