server:
  port: 8083

management:
  endpoint:
    chaosmonkey:
      enabled: true
  endpoints:
    web:
      exposure:
        include: '*'
chaos:
  monkey:
    enabled: false
    watcher:
      restController: true
      service: false
    assaults:
      latency-active: false
spring:
  profiles:
    active: chaos-monkey
  application:
    name: hot-deals
  cloud:
    kubernetes:
      enabled: false
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
dekorate:
  kubernetes:
    group: jackbeaken