server:
  port: 8089


# Init Chaos Monkey for Spring Boot by profile
spring:
  profiles:
    active: chaos-monkey
  application:
    name: httpbin
  cloud:
    kubernetes:
      enabled: false
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:9090/auth/realms/service/protocol/openid-connect/certs

# Configure Chaos Monkey - enabled = false
chaos:
  monkey:
#    enabled: false
    watcher:
      restController: true
      service: false
    assaults:
      latency-active: true

# Spring Boot Actuator Endpoint Chaos Monkey for Spring Boot
management:
  endpoint:
    chaosmonkey:
      enabled: true
    restart:
      enabled: true
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: '*'
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
dekorate:
  kubernetes:
    group: jackbeaken
logging:
  level:
    org.springframework.security: TRACE
