# APP DEPLOYMENT

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    run: gateway
  name: gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      run: gateway-exposed
  template:
    metadata:
      labels:
        run: gateway-exposed
    spec:
      serviceAccountName: chaos
      containers:
        - image: ryanjbaxter/gateway
          name: gateway
          ports:
            - containerPort: 8070
              protocol: TCP

---

# APP SERVICE

apiVersion: v1
kind: Service
metadata:
  labels:
    run: gateway
  name: gateway
spec:
  ports:
    - port: 8081
      protocol: TCP
      targetPort: 8070
  selector:
    run: gateway-exposed
  type: NodePort